% Isolate IDs and reconstruct with 1variable (191111)

% GAN WEI SHENG
% v20191224: modified from signalReconstruct
clear;
%% SETTINGS

load ../D_rsal_AC_191111.mat
%load D_rsal_171120_0.mat
ref_pos = 943*0.0025; %align timing
%VAR8


ID_select = {'61A0B2', '31E0D0', 'C09183', ...
                    'C04291', 'D0A110', '6181F0', ...
                    'D0B020', 'E0F270', 'F08373', ...
                    'E0B312', 'D01282', 'E00373', '0161A1'};


       
%VAR6
%{
 ID_select = {'70E1C1', ...
                    'D0A110', ...
                    'F08373', ...
                    '0161A1', ...
                    'C09183', ...
                    '6181F0', ...
                    '70F260', ...
                    '31E0D0',  ...
                    '515303', ...
                    '617242', ...
                    '80A1D0', ...
                    '61A0B2', ...
                    'C04291', ...
                    '8080A0', ...
                    '709183'};
%}

                
%VAR3
%{
ID_select = {'E0B312', ...
                    'D01282',...
                    'E00373',...
                    'D0B020',...
                    'C04291',...
                    '0161A1',...
                    'E0F270',...
                    '6181F0',...
                    'F08373',...
                    'C09183',...
                    'D0A110',...
                    '70E1C1'};
%}



%VAR4
%{
ID_select = {'70F260', ...
                    'E0B312',...
                    'D0B020',...
                    '70E1C1',...
                    'F08373',...
                    'D0A110',...
                    '018322',...
                    '6181F0',...
                    '80A1D0',...
                    '8080A0'} ;

%}

%VAR1
%{
ID_select = {'D0A110',...
                    '0161A1',...
                    'F08373',...
                    '903101',...
                    '6131F2',...
                    'E0F270',...
                    '31E0D0',...
                    '516173',...
                    '61A0B2',...
                    '90A1E2',...
                    '9011D2',...
                    'D01282'};
%}


%VAR2                

%{
ID_select = {'E0B312',...
                    'D0B020',...
                    'F08373',...
                    'E0F270',...
                    'D01282',...
                    'E00373',...
                    '0161A1',...
                    '6181F0',...
                    'C04291',...
                    'D0A110',...
                    '70E1C1',...
                    '018322',...
                    '80A1D0',...
                    '70F260',...
                    'C09183',...
                    '0161A1'};
%}

 %ID_select = {'512093', '2123C2', '5180A3', 'C07353'};

pcselect = [1:2]; %select pc to reconstruct
varSelect =1 %reconstruct variable

%% create new Dmatrix with selected ID

nID = numel(ID_select);
IDindx = false(1,nSample); 
%preallocation

%find ID index
for i = 1:nID
    IDindx = IDindx | strcmp(ID_select{i}, ID) ;
end

% create new matrix
newindx_sample = indx_class{1} | IDindx;  %OK + selected NG

Dnew = D(:, newindx_sample); % new D
nSample = size(Dnew, 2); %sample size
t_indx = t_indx(:, newindx_sample); %time vector
classSize(2) = nID;
ID = ID(newindx_sample);

indx_class{2} = false(1, nSample);
indx_class{2}(classSize(1)+1 : end)  = true;

D = Dnew;
%% SVD

newIndex = [indx_var{varSelect}];
D = D(newIndex,:);

[U, S, V] = svd(D); %SVD

% Reconstruct
Drecon =U(:,pcselect)*S(pcselect, pcselect)*V(:,pcselect)';

DzOKmean = mean(Drecon(:,indx_class{1}),2);
DzNGmean = mean(Drecon(:,indx_class{2}),2);

%% error and rescaling
% base_val = (Dz-a)*(max-min)/(b-a) + mim

minv = minval(varSelect);
maxv = maxval(varSelect);
a = 0;b = 1;

DzOKRescale =(DzOKmean-a)*(maxv-minv)./(b-a)+minv; %mean rescaled timeseries (OK)
DzNGRescale =(DzNGmean-a)*(maxv-minv)./(b-a)+minv; %mean rescaled timeseries (NG)

%Error = abs((DzOKRescale-DzNGRescale)./DzOKRescale*100);
Error = abs(DzOKRescale-DzNGRescale);
Error_percntg = Error./DzOKRescale*100;
%% plot mean OK/NG mean timeseries

t = 0: 0.0025: 0.0025*(len-1); %create time vector

figure;
ax=gca;
plot(t, DzOKRescale, classLine{1})
hold on
plot(t, DzNGRescale, classLine{2})
plot([ref_pos, ref_pos], [ax.YLim(1),  ax.YLim(2)])

yyaxis right
plot(t,Error, 'k--')
hold off

legend('OK mean', 'NG mean', 'Alginment Timing', 'Difference')

Error_perc_mean = median(Error_percntg);
fprintf('Mean error = %f\n', Error_perc_mean);

%% plot recon OK/NG timeseries

Drecon2 =U(:,:)*S(:, :)*V(:,:)';
Drecon_scaleback =(Drecon2-a)*(maxv-minv)./(b-a)+minv; %mean rescaled timeseries (OK)

t = 0: 0.0025: 0.0025*(len-1); %create time vector


figure;
ax = gca;
plot(t, Drecon_scaleback(:, indx_class{1}), classLine{1})
hold on
plot(t, Drecon_scaleback(:, indx_class{2}), classLine{2})
plot([ref_pos, ref_pos], [ax.YLim(1),  ax.YLim(2)])

%yyaxis right
%plot(t,Error, 'k--')
%hold off

legend('OK', 'NG')
